### ISSUE TITLE
configure instance-specific setting from outside

### ISSUE THREAD

**Issue by rhoerbe** [edushare-at/docker-etd#2]
it should not be required to have the instance # configured in the internal docker volume path, as in:

     map_docker_volume $mode "${CONTAINERNAME}.dataout" '/opt/data/out/PH08' 'Z' $DOCKERVOL_SHORT

**Comment by thomaswar** [comment]
It is not required. etd.py just needs that directory to exist when started with -o /opt/data
Note:
A later version of the etd will be able to choose one definition out of many from the config.
It is still a decision to make, if the etd sould be "tolerant" and create his output-dirs or "fail-safe" by failing with a configuration error if the output dirs do not exist, to make sure writing takes place, where it is intended.
